---
title: "workshop_script"
author: "Derrick Theophille"
format: html
---

```{r}
#| label: packages

library(tidyverse)
library(here)

# install.packages(c("FSA", "FSAdata", "nlstools")) # Fishery Stock Assessment and other tools

library(FSA) # Simple Fishery Stock Assessment methods
library(FSAdata) # data to support FSA package
library(nlstools) # Tools for nonlinear regression analysis
```


# Growth curves

Using the von Bertalanffy equation, where:
Linf: theoretical maximum length
K: growth coefficient
t0: theoretical age at zero length

```{r}
#| label: von Bertalanffy growth curve

age <- 1
TLage1 <- 607.7*(1-exp(-0.17*(age + 1.88)))
TLage1
```


```{r}
#| label: load csv file

allage <- read.csv(here("00_raw_data", "20230814.csv"), header = TRUE)

summary(allage)
head(allage)
tail(allage)
str(allage)
```

```{r}
#| label: plot-histogram-base-r

hist(allage$length)
```

```{r}
#| label: plot-histogram-ggplot

ggplot(data = allage,
       aes(x = length, 
           fill = as.factor(age))) +
  geom_histogram(position = "identity")

ggsave(here("03_plots", "lengths_comp.jpg"), height = 5, width = 5)
```

```{r}
#| label: Growth curve of yellowtail snapper length and age observations

age <- c(1:13)
# Total length mean is predicted
TLmean <- 607.7*(1-exp(-0.17*(age + 1.88)))

# Plot curve
plot(TLmean, type = "l")
# Plot points of observations
points(x = allage$age, y = allage$length)
```

```{r}
#| label: using-stock-assessment-tools

# Calculate appropriate initial values
f.start <- vbStarts(length ~ age, 
                    data = allage)

# Non-linear regression
growth <- nls(length ~ Linf*(1-exp(-K*(age-t0))), 
              data = allage,
              start = f.start)

overview(growth)
```

